apiVersion: v1
kind: Service
metadata:
  name: app-service-lb-preparation
spec:
  selector:
    app: fiap-preparation-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer