apiVersion: v1
kind: Service
metadata:
  name: app-service-preparation
spec:
  selector:
    app: fiap-preparation-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30008
  type: NodePort
